name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  style-lint-build:
    name: Style, Lint, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Setup npm
        uses: npm/action-setup@v4

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: Build the project
        run: npm run build
